DOMAIN = "inkbird_int14"
DEFAULT_NAME = "Inkbird INT-14"

SERVICE_UUID = "0000ff00-0000-1000-8000-00805f9b34fb"
LIVE_UUID = "0000ff01-0000-1000-8000-00805f9b34fb"
WRITE_UUID = "0000ff02-0000-1000-8000-00805f9b34fb"
STATE_UUID = "0000ff03-0000-1000-8000-00805f9b34fb"
BATTERY_UUID = "00002a19-0000-1000-8000-00805f9b34fb"

CONF_ADDRESS = "address"
CONF_NAME = "name"
CONF_MODEL = "model"
CONF_REQUEST_INIT_ON_CONNECT = "request_init_on_connect"
CONF_BLE_POLL_SECONDS = "ble_poll_seconds"
CONF_TRANSPORT_MODE = "transport_mode"
CONF_LAN_HOST = "lan_host"
CONF_LAN_DEVICE_ID = "lan_device_id"
CONF_LAN_LOCAL_KEY = "lan_local_key"
CONF_LAN_VERSION = "lan_version"
CONF_LAN_PORT = "lan_port"
CONF_LAN_POLL_SECONDS = "lan_poll_seconds"
CONF_LAN_TEST_ON_SETUP = "lan_test_on_setup"
CONF_CLOUD_HISTORY_ENABLED = "cloud_history_enabled"
CONF_CLOUD_API_KEY = "cloud_api_key"
CONF_CLOUD_API_SECRET = "cloud_api_secret"
CONF_CLOUD_PRODUCT_ID = "cloud_product_id"
CONF_CLOUD_DEV_ID = "cloud_dev_id"
CONF_CLOUD_COUNTRY_CODE = "cloud_country_code"
CONF_CLOUD_BASE_URL = "cloud_base_url"
CONF_CLOUD_POLL_SECONDS = "cloud_poll_seconds"

DEFAULT_CLOUD_BASE_URL = "https://us.api-inkbird.com/api/"
DEFAULT_BLE_POLL_SECONDS = 10
DEFAULT_CLOUD_POLL_SECONDS = 60
DEFAULT_LAN_POLL_SECONDS = 10
DEFAULT_LAN_PORT = 6668
DEFAULT_LAN_VERSION = 3.5

TRANSPORT_MODE_AUTO = "Auto"
TRANSPORT_MODE_BLE_ONLY = "BLE only"
TRANSPORT_MODE_WIFI_LAN_ONLY = "Wi-Fi LAN only"
TRANSPORT_MODE_WIFI_CLOUD_ONLY = "Wi-Fi cloud only"
TRANSPORT_MODES = (
    TRANSPORT_MODE_AUTO,
    TRANSPORT_MODE_BLE_ONLY,
    TRANSPORT_MODE_WIFI_LAN_ONLY,
    TRANSPORT_MODE_WIFI_CLOUD_ONLY,
)
